### ISSUE TITLE
getUsersIssues returns JQL error

### ISSUE THREAD

**Issue by m00g33k** [jira-node/node-jira-client#115]
Error
`"400 - {"errorMessages":["Error in the JQL Query: 'true' is a reserved JQL word. You must surround it in quotation marks to use it in a query. (line 1, character 80)"],"errors":{}}"`

Code
`jira.getUsersIssues('myusername',true)`

**Comment by KanoYugoro** [comment]
Instead of passing a boolean true, if you passed a string `"\"true\""` it would most likely solve the error you're seeing.  You're welcome to submit a pull request to the repo to add quotes to the interpolated string inside that method as a long term solution.
