### ISSUE TITLE
Consider breaking the fork dependency for your repo

### ISSUE THREAD

**Issue by JamesMGreene** [jira-node/node-jira-client#137]
Consider breaking the fork dependency for your repo to get full GitHub functionality (code search, etc.).  Seems like [steves/node-jira](https://github.com/steves/node-jira) has ceased all updates, so just adding an attribution note into your README and breaking the fork seems like a good idea to me.

To do so, just [contact GitHub Support](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork).  This is a quick and easy request for them to handle.

**Comment by KanoYugoro** [comment]
This really isn't a bad idea at this point.  I just haven't had the time to do coding outside of work recently.  I'll look and see if I have some time this weekend to do it.

**Comment by JamesMGreene** [comment]
:+1:
