### ISSUE TITLE
Update request-promise to v.4.0.0

### ISSUE THREAD

**Issue by shmuga** [jira-node/node-jira-client#139]
Due to this bug https://github.com/request/request-promise/issues/91 it would be nice if  you to update `request-promise` dependency. 
It will fix problems with bundlers and your lib 👍

**Comment by KanoYugoro** [comment]
I will have to do a large update as I have not had time to get the dependencies updated, and I know I'm on an old version of babel.

**Comment by KanoYugoro** [comment]
Fixed in #158
