### ISSUE TITLE
Add "dev-status" API

### ISSUE THREAD

**Issue by JamesMGreene** [jira-node/node-jira-client#142]
JIRA has an undocumented "dev-status" API that is usual when JIRA is integrated with other tools like Stash (Bitbucket Server).  For example:

### To get info about branches and pull requests related to an issue:

https://{jiraHost}/rest/dev-status/latest/issue/detail?issueId={jiraIssueNumericId}&applicationType=stash&dataType=pullrequest

### To get info about commits related to an issue:

https://{jiraHost}/rest/dev-status/latest/issue/detail?issueId={jiraIssueNumericId}&applicationType=stash&dataType=repository

I can also supply scrubbed example response bodies if desired.

**Comment by KanoYugoro** [comment]
Feel free to submit a PR.  I haven't had time to maintain this lately.  😄

**Comment by jeffbaldwinjr** [comment]
I am actually super interested in this, I will see if I can do anything to add these.

@JamesMGreene I assume both of these are GET calls?

**Comment by 3zzy** [comment]
There's also one for the **summary**: 

https://{jiraHost}/rest/dev-status/latest/issue/summary?issueId={jiraIssueNumericId}

**Comment by JamesMGreene** [comment]
@3zzy Good call. Luckily, that was already added in PR #177 as well.
