### ISSUE TITLE
Add "agile" API

### ISSUE THREAD

**Issue by JamesMGreene** [jira-node/node-jira-client#143]
JIRA has effectively deprecated the undocumented GreenHopper API and introduced a new Agile API to, uhh, sort-of take its place (although the GreenHopper API is still way more useful than its replacement, IMHO).

 - [JIRA Agile Cloud docs](https://docs.atlassian.com/jira-software/REST/cloud/)
 - [JIRA Agile Server docs](https://docs.atlassian.com/jira-software/REST/server/)

**Comment by jeffbaldwinjr** [comment]
This issue should be fixed with #179 #180 #181 #182
