### ISSUE TITLE
Add support for "fields" query param on `findIssue` method

### ISSUE THREAD

**Issue by JamesMGreene** [jira-node/node-jira-client#144]
It would be great to be able to restrict the fields returned for an issue for the `findIssue` method by using the "fields" query param that the REST API already supports:

https://docs.atlassian.com/jira/REST/server/#api/2/issue-getIssue

**Comment by JamesMGreene** [comment]
P.S. There is already support for this query param in some other method(s), like `searchJira`.

**Comment by KanoYugoro** [comment]
There's a few different functions in this package that should have similar logic consolidated.  If I have time this weekend to give this some love, I'll look into doing it.   Otherwise I'm open to accepting PRs.

**Comment by MeTaNoV** [comment]
it would indeed be pretty handy! :) Any update?
