### ISSUE TITLE
getUsersIssues JQL Error

### ISSUE THREAD

**Issue by cmbirk** [jira-node/node-jira-client#149]
I'm using JiraApi.getUsersIssues like so:

```
jira.getUsersIssues ('@someone', false)
```
and getting an error: 

```
{"errorMessages":["Error in the JQL Query: Expecting either 'OR' or 'AND' but got 'false'. (line 1, character 65)"],"errors":{}}
```

In looking at the function in the code, it looks like `open` is just being concatenated - 

```
key: 'getUsersIssues',
    value: function getUsersIssues(username, open) {
      return this.searchJira('assignee = ' + username.replace('@', '\\u0040') + ' ' + ('AND status in (Open, \'In Progress\', Reopened) "' + open + '"'), {});
    }
```

It seems like this should affect the included status array instead of just being concatenated.

**Comment by maurelio1234** [comment]
I just found this error, it's just that in my case I was calling it with `open=true`, and getting an out of memory.

Should it be something like that ?

`(open  ? 'AND status in (Open, \'In Progress\', Reopened) "' : '')`

**Comment by KanoYugoro** [comment]
We do accept pull requests.

**Comment by maurelio1234** [comment]
Just create a PR on this issue: https://github.com/jira-node/node-jira-client/pull/154

**Comment by KanoYugoro** [comment]
Closing this because the PR got merged.  Sorry it took me so long to get back to you.
