### ISSUE TITLE
Add override for api version

### ISSUE THREAD

**Issue by kavehsajjadi** [jira-node/node-jira-client#159]
Hey mang,

we have a jira server we're using, would be nice if I could provide a function or something to override the pathname generated in makeUri because we have
example.com/rest/____
and get 404's when /api/${apiVersion} is in there.

**Comment by KanoYugoro** [comment]
This seems like a pretty reasonable request.  If you'd like to submit a PR, I'd be more than happy to consider it.  Otherwise, I'll get around to doing something like this sometime soon.

**Comment by JamesMGreene** [comment]
I'm not following.  What is the desired URL and what is the URL you are ending up with?

**Comment by kavehsajjadi** [comment]
@JamesMGreene the issue I'm experiencing is
generated: http://www.example.com/rest/api/2/pathname
desired: http://www.example.com/rest/pathname
at the moment I'm just overriding the makeUri method in my helper script but it would be nice to be able to be able to override it in a more natural way.

@KanoYugoro I was just checking this to write some code myself and saw the PR.
I was going to apply a function that replaces the makeUri completely rather than just a string change but this solves my problem all the same.
Thanks for looking to this so fast!

**Comment by KanoYugoro** [comment]
Released version v6.0.1, as the change should be completely backwards compatible.
