### ISSUE TITLE
Documentation link not obvious

### ISSUE THREAD

**Issue by goldcaddy77** [jira-node/node-jira-client#161]
Not sure if anybody else has missed the documentation badge, but I have a couple times.  Does it make sense to call out the documentation in it's own section of the readme?

<img width="609" alt="screen shot 2017-03-29 at 8 25 49 pm" src="https://cloud.githubusercontent.com/assets/573625/24482275/0ace9332-14be-11e7-92bf-a9b9a0183c73.png">

**Comment by KanoYugoro** [comment]
That sounds reasonable.  I'll put in another more obvious link in addition.

**Comment by goldcaddy77** [comment]
Great, thanks!

**Comment by KanoYugoro** [comment]
Added a link at the bottom.
