### ISSUE TITLE
cannot create jira client

### ISSUE THREAD

**Issue by zeuyanik** [jira-node/node-jira-client#164]
I follow the documentation and insert my credentials to the required fields but couldn't login. 
It throws an error as; 

> RequestError: Error: tunneling socket could not be established, cause=socket hang up

	var JiraApi = require('jira-client');
	// Initialize
	var jira = new JiraApi({
		protocol: 'https',
		host: '@hostname',
		username: '@username',
		password: '@password',
		apiVersion: '2',
                strictSSL: true
	});

	jira.findIssue(@issueNumber)
		.then(function(issue) {
			console.log('Status: ' + issue.fields.status.name);
		})
		.catch(function(err) {
			console.error(err);
		});

I'm behind corporate proxy is it the problem? I couldn't even define the problem. It just hangs up. What do you suggest me?

**Comment by KanoYugoro** [comment]
This is beyond my capability to diagnose, but if I had to guess, the request to your instance of JIRA is being sent off and allowed through your proxy / firewall, but the response cannot make it back to your machine.

**Comment by KanoYugoro** [comment]
This has been open for a week with no new context and no one chiming in.  Since it is out of my hands, I'm going to close this issue.
