### ISSUE TITLE
How to download project image?

### ISSUE THREAD

**Issue by alexcroox** [jira-node/node-jira-client#166]
I need to save a project image locally so I can serve it up to the user, however it seems I need to make an authenticated API call to get the image data for `project.avatarUrls['32x32']` which might look like `https://xxx.atlassian.net/secure/projectavatar?size=small&pid=xxx&avatarId=xxx`. 

Is this something the library already supports and I'm just missing it?

**Comment by KanoYugoro** [comment]
If it's not listed in the documentation link, which can be found at the top and bottom of the readme, then this package doesn't support it.  I don't believe we have this functionality off the top of my head, so you're welcome to submit a PR to add it if you'd like.

**Comment by alexcroox** [comment]
No worries I noticed a bunch of things I wanted to call weren't yet included so decided to roll my own class to interact with the API. Thank you though.
