### ISSUE TITLE
Add Option for Bearer Token Authentication

### ISSUE THREAD

**Issue by jeffbaldwinjr** [jira-node/node-jira-client#167]
It would be nice to be able to use a previously retrieved Bearer token. I currently use Atlassian's OAuth client to retrieve and OAuth token using the JWT. I think the easiest way to incorporate that feature is to just modify the Authentication to accept Bearer... or if you are willing to accept JWT and have that create an OAuth token that would be even better.

**Comment by KanoYugoro** [comment]
You're welcome to submit a PR for this functionality

**Comment by jeffbaldwinjr** [comment]
@KanoYugoro Submitted. Wasn't as hard as I thought.

**Comment by KanoYugoro** [comment]
Released v6.2.0 with your changes

**Comment by JamesMGreene** [comment]
This option is not documented as part of the [`JiraApiOptions` typedef](https://jira-node.github.io/typedef/index.html#static-typedef-JiraApiOptions), though.
