### ISSUE TITLE
Can't use addWorklog

### ISSUE THREAD

**Issue by caioflores** [jira-node/node-jira-client#193]
I'm trying to use the addWorklog method without success. Can anyone help me?

This is my worklog object: 
```javascript
const worklog = {
      "started": "2017-03-31T13:39:13.106+0000",
      "timeSpent": "3h 20m",
      "newEstimate": "1d",
}
```
And I get this error: "400 - {"errorMessages":["Unrecognized field \"newEstimate\"...

But when I try it without the newEstimate field I get this error: "400 - {"errorMessages":["Worklog must not be null."],"errors":{"newEstimate":"You must supply a valid new estimate."}}"

**Comment by pioug** [comment]
We patched `addWorklog` in the [v6.5.1](https://github.com/jira-node/node-jira-client/releases/tag/v6.5.1), feel free to reopen the issue if it still doesn't work for you.
