### ISSUE TITLE
Empty properties string causing Internal Server Error on findIssue API call

### ISSUE THREAD

**Issue by gedrick** [jira-node/node-jira-client#201]
On JIRA API v2, passing in an empty properties query string param is causing an Internal Server Error. Removing the param entirely or setting it to a `*` fixes the issue. url.format takes null or undefined values in the querystring and sets them to an empty string.

Changing the following line:

```javascript
properties: properties || '',
```
to

```javascript
properties: properties || '*',
```

Correctly formats the querystring and findIssue returns valid json.

**Comment by gedrick** [comment]
More details available here: https://docs.atlassian.com/jira/REST/cloud/#api/2/issue

Looks like `*all` is the preferred method.

```
*all - include all properties
```

**Comment by metaodi** [comment]
Same as #187
