### ISSUE TITLE
request-promise now need the request dependency, should this project add it?

### ISSUE THREAD

**Issue by afucher** [jira-node/node-jira-client#209]
I try to use this module, but I have an error saying that "The "request" library is not installed automatically anymore", searching for the reason I find [that ](https://github.com/request/request-promise#migration-from-v3-to-v4) the `request-promise` project need it.  

Should `request` be a dependency of this project?  

I can send a PR for this, if it make sense...

**Comment by pioug** [comment]
Added in https://github.com/jira-node/node-jira-client/releases/tag/v6.5.0.
