### ISSUE TITLE
Basic auth with password to be deprecated on Jira cloud APIs - start using API tokens 

### ISSUE THREAD

**Issue by mansilladev** [jira-node/node-jira-client#217]
See: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

As of March 15, 2018, in accordance to the [Atlassian REST API Policy](https://developer.atlassian.com/platform/marketplace/atlassian-rest-api-policy/), support for passwords in HTTP basic auth requests will no longer be supported on or after September 15, 2018.

Instead of passwords, you should start using [API tokens](https://confluence.atlassian.com/cloud/api-tokens-938839638.html).

**Comment by jeremieca** [comment]
+1 essential functionality !

**Comment by armand1m** [comment]
+1, also is really simple

**Comment by toyerma** [comment]
Has anyone implemented API Tokens or any other authentication method besides the username/password option on this api?. Example code please.

**Comment by CapsuleMaglev** [comment]
It seems that basic auth has been deprecated for good. Anyone else having issues with the API?

**Comment by UlianaPavelko** [comment]
> It seems that basic auth has been deprecated for good. Anyone else having issues with the API?
> Edit: I switched the password for the API Token and it seems to be working as before.

Can you provide a code example?

**Comment by CapsuleMaglev** [comment]
> 
> 
> > It seems that basic auth has been deprecated for good. Anyone else having issues with the API?
> > Edit: I switched the password for the API Token and it seems to be working as before.
> 
> Can you provide a code example, please?

When instancing the JiraApi variable use:
// Initialize
var jira = new JiraApi({
  protocol: 'https',
  host: 'jira.somehost.com',
  username: 'username',
  password: '**TOKEN**',
  apiVersion: '2',
  strictSSL: true
});

Should work right away if your token is valid

**Comment by armand1m** [comment]
I dropped this library and started calling the API's from JIRA using plain `fetch` calls instead.

**Comment by UlianaPavelko** [comment]
> > > It seems that basic auth has been deprecated for good. Anyone else having issues with the API?
> > > Edit: I switched the password for the API Token and it seems to be working as before.
> > 
> > 
> > Can you provide a code example, please?
> 
> When instancing the JiraApi variable use:
> // Initialize
> var jira = new JiraApi({
> protocol: 'https',
> host: 'jira.somehost.com',
> username: 'username',
> password: '**TOKEN**',
> apiVersion: '2',
> strictSSL: true
> });
> 
> Should work right away if your token is valid

Thank you @CapsuleMaglev it does work!

**Comment by lcesarmonteiro** [comment]
@CapsuleMaglev as username you mean email? what username is that?
