### ISSUE TITLE
SearchJira function does not filter by entered JQL query, simply returns all issues

### ISSUE THREAD

**Issue by Tauroctonos** [jira-node/node-jira-client#218]
I've found that no matter what I do to the JQL query (including making it invalid or simply removing it and calling the function without the parameter) I am returned a full list of all the issues my api has access to.

**Comment by Tauroctonos** [comment]
Found a workaround.

If you enter the host as 'jira.somehost.com/jira' everything works as it should. Usually it redirects URIs without the '/jira', but for whatever reason it isn't doing it with our requests.

**Comment by ohashi808** [comment]
Getting this issue as well but with the cloud version of JIRA.

Setting protocol to `https` in the API options worked for us as a workaround.
