### ISSUE TITLE
updateIssue - notifyUsers  not working

### ISSUE THREAD

**Issue by srl295** [jira-node/node-jira-client#228]
hi.

https://developer.atlassian.com/cloud/jira/platform/rest/#api-api-2-issue-issueIdOrKey-put says there's a `notifyUsers: false` option

but the API https://jira-node.github.io/class/src/jira.js~JiraApi.html#instance-method-updateIssue does not mention it, nor is it in the code.

calling `jira.updateIssue(issueKey, {fields, notifyUsers: false})` seems to have no effect (users get notified about assignments/etc).

**Comment by ab320012** [comment]
I think notifyUser is a query string param according to the docs for which there isn't an interface

https://github.com/jira-node/node-jira-client/blob/master/src/jira.js#L698

maybe can modify the signature of updateIssue to take one more object that parses to query string

**Comment by pioug** [comment]
Fixed in https://github.com/jira-node/node-jira-client/releases/tag/v6.5.1.
