### ISSUE TITLE
The "request" library is not installed automatically anymore

### ISSUE THREAD

**Issue by slavafomin** [jira-node/node-jira-client#230]
Hello!

Thank you for this great library!

However, when trying to use it I get the following error:

```
###
### The "request" library is not installed automatically anymore.
### But required by "request-promise".
###
### npm install request --save
###

./node_modules/request-promise/lib/rp.js:23
    throw err;
    ^

Error: Cannot find module 'request'
...
```

You should add the `request` dependency to this module's `package.json` file, because `request-promise` is not enough theses days.

Thanks!

**Comment by pioug** [comment]
Fixed with https://github.com/jira-node/node-jira-client/commit/b9927666b3d3d3ab46ea23b2fa2263afc16d5776
