### ISSUE TITLE
RequestError: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by poloka** [jira-node/node-jira-client#241]
Simple api call receiving error in fetching results.  I can see in the network tab of my chrome browser that the call to components returned a 200.  Copy the request URL and paste into another tab and the JSON returns as expected.  What could cause the inability to 'fetch' results?

```
    const jira = new JiraApi({
      protocol: 'https',
      host: '<host>',
      apiVersion: 'latest',
    })

    jira.listComponents('ION')
      .then((components) => {
        alert('in success')
        alert(components)
      })
      .catch((err) => {
        alert(err)
      });
```

**Comment by poloka** [comment]
I do see in my console
```
Cross-Origin Read Blocking (CORB) blocked cross-origin response <host> with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```
Is there a way to pass the header `Access-Control-Allow-Origin` for these requests?

**Comment by dkokic** [comment]
@poloka Am I wrong in assumption that you are trying to run this on client (in web browser)? ;-)

**Comment by poloka** [comment]
@dkokic you are correct.  I have created a simple react app using [create-react-app](https://github.com/facebook/create-react-app) and tried to implement the jira-client.  So I'm running this from localhost.

**Comment by pioug** [comment]
"Cross-Origin" things usually needs a server configuration. It's between the browser and the server. I am afraid there is nothing we could solve in the scope of this module. 

Moreover, `node-jira-client` is build on top of `request` and `request-promise` https://www.npmjs.com/package/request and I don't think they are designed to work inside a browser..

There is certainly a way to refactor everything and make it work in a browser though.

**Comment by Ahmar828** [comment]
@pioug did you find any solution? i am having same issue.

**Comment by pioug** [comment]
@Ahmar828 Try this client https://github.com/MrRefactoring/jira.js. Seems like it is build on axios, so it may work both in browser and node. If you have `blocked cross-origin response` it can't be solve by any lib, you need to configure the endpoint server.
