### ISSUE TITLE
TypeError: jira_client_1.default is not a constructor

### ISSUE THREAD

**Issue by b1zzu** [jira-node/node-jira-client#253]
I have created a very simple Typescript file that imports the JiraApi:
```typescript
import JiraApi from "jira-client";

this.client = new JiraApi({
  host: JIRA_HOST,
  password: JIRA_PASSWORD,
  protocol: JIRA_PROTOCOL,
  username: JIRA_USERNAME
});
```
but when I execute it using ts-node I get this error:
```
TypeError: jira_client_1.default is not a constructor
```
I have tried to change the import to:
```
import * as JiraApi from "jira-client"
```
and I get a typescript error:
```
error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature
```
but if I prefix `new JiraApi()` with `// @ts-ignore` the script works but I completely lose typescript support.

Also if I remove the add-module-exports bable plugin and I rebuild the jira-client than it works perfectly using `import JiraApi from 'jira-client'`.

I know this is not a blocking issue but maybe we can do something to restore typescript support with ts-node.

**Comment by b1zzu** [comment]
Another way I found to fix it is:
```typescript
export = JiraApi;
``` 
instant of 
```typescript
export default JiraApi;
```
in the typescript definition `index.d.ts`

**Comment by bogdan-calapod** [comment]
Also experiencing this.

**Comment by pioug** [comment]
I suppose you're using the types from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jira-client/index.d.ts. The issue should be reported there I think.

**Comment by adam-kiss-sg** [comment]
This worked for me:
```
import * as JiraApi from 'jira-client';
```

@pioug this seems to be a documentation issue. The "import" example in the [documentation](https://www.npmjs.com/package/jira-client) does not work, event without the jira types (throws the error reported by @b1zzu ). 

Can you please re-open?

**Comment by pioug** [comment]
@adam-kiss-sg Can you share a repro case?

```js
import JiraApi from 'jira-client';

// Initialize
var jira = new JiraApi({
  protocol: 'https',
  host: 'jira.somehost.com',
  username: 'username',
  password: 'password',
  apiVersion: '2',
  strictSSL: true
});

console.log(jira);
console.log(jira.findIssue);
```

```
~/Dev/node-jira-test 
> node index.js
JiraApi {
  protocol: 'https',
  host: 'jira.somehost.com',
  port: null,
  apiVersion: '2',
  base: '',
  intermediatePath: undefined,
  strictSSL: true,
  request: [Function: request],
  webhookVersion: '1.0',
  greenhopperVersion: '1.0',
  baseOptions: { auth: { user: 'username', pass: 'password' } }
}
[Function: findIssue]
```

**Comment by adam-kiss-sg** [comment]
Hi!

Well, this is strange. I tried a minimal reproduction with ts:

package.json:
```
{
  "name": "repro",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "ts-node index.ts"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jira-client": "^8.2.2",
    "ts-node": "^10.9.1"
  }
}
```

index.ts:
```
// @ts-ignore
import JiraApi from 'jira-client';

// Initialize
var jira = new JiraApi({
  protocol: 'https',
  host: 'jira.somehost.com',
  username: 'username',
  password: 'password',
  apiVersion: '2',
  strictSSL: true
});

console.log(jira);
console.log(jira.findIssue);
```

Then run `npm run start`, and the output is the same as yours.

But if I add in an empty (0 bytes) tsconfig.json, I see the error: `TypeError: jira_client_1.default is not a constructor...`

If I change the import to `import * as JiraApi from 'jira-client';`, it works again.

Hope that helps.

**Comment by pioug** [comment]
It seems like `ts-node` is doing something extra. It probably requires extra configuration on your end.

**Comment by pioug** [comment]
@adam-kiss-sg Please check:

https://www.google.com/search?q=default+is+not+a+constructor+ts+node
https://stackoverflow.com/a/64213538
https://github.com/web3/web3.js/issues/4301
https://github.com/TypeStrong/ts-node/issues/520

This repo don't do TS, so I personally prefer to not change anything there
