### ISSUE TITLE
Getting 401 unauthorized when I make call

### ISSUE THREAD

**Issue by crhistianramirez** [jira-node/node-jira-client#255]
I should say I was logging in with my credentials just fine for the longest time but now I'm getting a 401 when I make my a call. I can login on the website and I even changed my password to see if that might do the trick but no go. 

I'm testing with the code from readme:

```javascript
var JiraApi = require('jira-client');
 
// Initialize
var jira = new JiraApi({
  protocol: 'https',
  host: MY_HOST,
  username: MY_USERNAME,
  password: MY_PASSWORD,
  apiVersion: '2',
  strictSSL: false
});

jira.findIssue("AV-168")
  .then(function(issue) {
    console.log('Status: ' + issue.fields.status.name);
  })
  .catch(function(ex) {
    // fails here and I get an html page with status 401
    console.error(ex.message);
  });
```

**Comment by crhistianramirez** [comment]
Found out this is actually related to jira [deprecating basic auth](https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html).

I generated an api token and set that as my password.

**Comment by aequasi** [comment]
Even using an api token i get `{"message":"Client must be authenticated to access this resource.","status-code":401}`, with 
![image](https://user-images.githubusercontent.com/896295/67607441-57381300-f739-11e9-8179-1b830a6fd67a.png)

**Comment by lcesarmonteiro** [comment]
@crhistianramirez I generated a Token and a Key and I am using as username and password. What did you use as username and password?

**Comment by crhistianramirez** [comment]
Username is the same (in my case my email address). The only thing that I changed is that I used the api token *instead of* my password.
