### ISSUE TITLE
SearchJira function does not take in 'expand' option for typescript

### ISSUE THREAD

**Issue by marlenekoh** [jira-node/node-jira-client#256]
Hi, I'm using typescript and have installed `@types/jira-client`.

However, when using the `searchJira` api, I am unable to pass `expand` as an option because it is not included in the SearchQuery Interface
> searchJira(searchString: string, optional?: JiraApi.SearchQuery): Promise<JiraApi.JsonResponse>;

```
    interface SearchQuery {
        startAt?: number;
        maxResults?: number;
        fields?: string[];
        expand?: string[]; // this line is missing from the index.d.ts file
    }
```

However, it is [documented in the api](https://jira-node.github.io/class/src/jira.js~JiraApi.html#instance-method-searchJira) that the expand param is supported. I have manually added the expand field to the interface and doing
```
jiraApi.searchJira("assignee in (currentUser()) AND sprint in openSprints()", { expand: ["renderedFields"]}
```
 works as expected - it returns the renderedFields of each issue belonging to the current user in the active sprint

**Comment by pioug** [comment]
Oh, I just found out about `@types/jira-client`. Unfortunately, I can't really help since it's not maintain here. Issue must be reported in https://github.com/DefinitelyTyped/DefinitelyTyped.
