### ISSUE TITLE
SearchJira function is returning only 100 issues, not honoring maxResults option

### ISSUE THREAD

**Issue by praveendandu** [jira-node/node-jira-client#258]
SearchJira function is returning only 100 issues, not honoring maxResults option

**Comment by randyho-kk** [comment]
Not a bug.  This is by design and part of the API

> The maximum number of items to return per page. To manage page size, Jira may return fewer items per page where a large number of fields are requested. The greatest number of items returned per page is achieved when requesting id or key only.

https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-search-get
