### ISSUE TITLE
Add support for setting visibility for added comment.

### ISSUE THREAD

**Issue by tlaukkan** [jira-node/node-jira-client#259]
Thank you for this library, its a real time saver. Would need to set visiblity for added comment though and the current API call does not include that as parameter yet.

https://developer.atlassian.com/server/jira/platform/jira-rest-api-example-add-comment-8946422/

{
    "body": "This is a comment that only administrators can see.",
    "visibility": {
        "type": "role",
        "value": "Administrators"
    }
}

**Comment by tlaukkan** [comment]
For example this works:

  /** Add a comment to an issue
   * [Jira Doc](https://docs.atlassian.com/jira/REST/latest/#id108798)
   * @name addComment
   * @function
   * @param {string} issueId - Issue to add a comment to
   * @param {string} comment - string containing comment
   * @param {string} visibleToRole - if set comment visibility is restricted to this role
   */
  addComment(issueId, comment, visibleToRole) {
    return this.doRequest(this.makeRequestHeader(this.makeUri({
      pathname: `/issue/${issueId}/comment`,
    }), {
      body: {
        body: comment,
        visibility: visibleToRole !== undefined ? {
          type: "role",
          value: visibleToRole
        } : undefined
      },
      method: 'POST',
      followAllRedirects: true,
    }));
  }

Type definition:

    public addComment(issueId: string, comment: string, visibleToRole: string | undefined = undefined): Promise<JiraApi.JsonResponse>;

**Comment by pioug** [comment]
I think `addCommentAdvanced` can be used in this case https://jira-node.github.io/class/src/jira.js~JiraApi.html#instance-method-addCommentAdvanced

```js
addCommentAdvance(issueId, {
  body: comment,
  visibility: {
    type: "role",
    value: visibleToRole,
  },
});
```

In general I would advise against this kind of signature `addComment(issueId, comment, visibleToRole)`. Remapping a list of arguments into an payload object doesn't have much value. Validating every argument is very error prone. It's just simpler to let that in the userland. It also super hard to keep this kind of API consistent with all the other methods.
