### ISSUE TITLE
Incorrect Webhooks API URL

### ISSUE THREAD

**Issue by jelly972** [jira-node/node-jira-client#26]
Although this is Atlassian issue, at the moment it is holding me back.

Webhooks is not listed under JIRA official documentation (https://docs.atlassian.com/jira/REST/latest/), it is listed under the webhooks documentation (https://developer.atlassian.com/jiradev/jira-apis/webhooks#Webhooks-re) under the following URL:
<JIRA_URL>/rest/webhooks/1.0/webhook/
which doesnt conform to the default URL defind in 'makeUri' function at line 143:
"pathname: this.base + '/rest/api/' + this.apiVersion + pathName"

**Comment by KanoYugoro** [comment]
Ah.  You'll have to forgive me.  When I went through and updated everything, I missed this.  Though that is annoying that the webhook documentation isn't in the jira rest API documentation.  I'll write a quick fix for this.
