### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by DanielRuf** [jira-node/node-jira-client#267]
I propose to migrate to GitHub Actions which is more flexible and faster =)

**Comment by dkokic** [comment]
Any proposal for GitHub workflow file? ;-)

**Comment by DanielRuf** [comment]
Sure, in general it is quite easy.

2 jobs, one with the `node:latest` container and one with the NodeJS `8, 10, 12` versions using `actions/setup-node`.

https://github.com/DanielRuf/filter-webpack-plugin/blob/master/.github/workflows/main.yml#L29

https://github.com/DanielRuf/filter-webpack-plugin/blob/master/.github/workflows/main.yml#L10

**Comment by pioug** [comment]
I did the migration 🙌  The immediate benefit is not having to deal with permissions on Travis side and sharing workflows with contributors.
