### ISSUE TITLE
Reply to comment

### ISSUE THREAD

**Issue by chennn1990** [jira-node/node-jira-client#271]
Is there a possibility for reply to an existing comment?
I found no hint of this ability through the documentation.
Thanks

**Comment by kentora** [comment]
Jira does not support threads in comments - so what you want to do is add a new comment. This can be done via `addComment(issueKey, commentString)`

**Comment by Ore4444** [comment]
@kentora actually in our office we use comment threads in JIRA all the time. In the JIRA UI it is possible. Clicking "Comment" adds a top-level comment to the issue, while clicking "reply" on any of the existing comments adds a nested comment. Multiple nesting levels are supported
<img width="706" alt="_SPLWX-4657__Test_-_sync_live_status_-_automation_-_base_-_IronSource_JIRA_-_AWS_Production" src="https://user-images.githubusercontent.com/2034481/79430328-740b2000-7fd1-11ea-9f89-00f1720691f9.png">

**Comment by kentora** [comment]
@Ore4444 The functionality is provided by an add on - not by Jira itself.
It does not seem to be possible through the API, but maybe you could post the results from getting the comments here? Maybe it is simply metadata in the comments?

**Comment by Ore4444** [comment]
@kentora wow you're right. This feature did come from [an addon](https://marketplace.atlassian.com/apps/1212145/threaded-comments-for-jira?hosting=server&tab=installation). Looking at the API response, the comments are flat and not associated with one another (no child-parent relationship) even though in JIRA UI they are nested. I wonder then where is the association persisted?..
<img width="865" alt="Firefox_Developer_Edition" src="https://user-images.githubusercontent.com/2034481/79436168-301c1900-7fd9-11ea-9c4e-ceba40e7e2f1.png">
Anyway I see now this is a non-issue. Thanks!

**Comment by randyho-kk** [comment]
Looks like the threaded comments addon writes directly to sql and not through the JIRA API to achieve comment threading.  The migration docs for it shows this:

```
INSERT INTO AO_0C0737_COMMENT_INFO(COMMENT_ID, ISSUE_ID,PARENT_COMMENT_ID) SELECT COMMENT_ID, ISSUE_ID,PARENT_COMMENT_ID FROM AO_CFEE31_COMMENT_INFO;
INSERT INTO AO_0C0737_VOTE_INFO(COMMENT_ID, ISSUE_ID,USER_NAME,VOTE_COUNT) SELECT COMMENT_ID, ISSUE_ID,USER_NAME,VOTE_COUNT FROM AO_CFEE31_VOTE_INFO;
```
https://bitbucket.org/vrenjith/jira-threaded-comments/wiki/Migrating%20From%20Atlassian%20Labs%20Add-on


This, since it's not available via the API.  I'm closing this out.
