### ISSUE TITLE
Change adjustEstimate other value then new or auto in Addworklog

### ISSUE THREAD

**Issue by elweilando** [jira-node/node-jira-client#273]
With node-jira-client I can only set the newEstimate in addWorklog in jira.js Line 1423.
[Jira API](https://developer.atlassian.com/cloud/jira/platform/rest/v3/?_ga=2.112172866.737250867.1582056562-1148298315.1580807675#api-rest-api-3-issue-issueIdOrKey-worklog-post) can also set the adjustEstimate Value to other values then new (with newEstimate) and auto.

How can I add the query-parameters to adjustEstimate = leave?

**Comment by pioug** [comment]
Solved in https://github.com/jira-node/node-jira-client/commit/25b53ef9c5c9515839653dd16724a47dd290e1d6.

```js
addWorklog(issueId, worklog, newEstimate, { adjustEstimate: 'leave })
```
