### ISSUE TITLE
Issue ID Documentation Out of Sync

### ISSUE THREAD

**Issue by drtootsie** [jira-node/node-jira-client#284]
In the majority of the places, the issueId is called out as a string (https://github.com/jira-node/node-jira-client/blob/master/src/jira.js#L434)

In the getComments and getComments functions, it's labeled as a number.

**Comment by drtootsie** [comment]
This is linked to this issue https://github.com/jira-node/node-jira-client/pull/283

**Comment by pioug** [comment]
Thanks for you contribution! Merged https://github.com/jira-node/node-jira-client/pull/283
