### ISSUE TITLE
searchUsers method stopped working as expected

### ISSUE THREAD

**Issue by DanielPe05** [jira-node/node-jira-client#285]
Per Jira's documentation:
```
NOTE: Personal data that is used to identify users, such as username and userKey, has been removed from the Jira Cloud REST APIs. In addition, other personal data (for example, email) is now restricted by a user's profile settings (or in the case of managed accounts, the visibility settings decided by the site administrator). You must update your apps to accommodate these changes, if you have not done so already. This change was previously announced on 01 October 2018 and followed by a deprecation period (see the announcement).
```

Which caused methods like `jira.searchUsers({ username: email })` to stop working. The work around I were able to find was hitting the following endpoint: `https://redventures.atlassian.net/rest/api/2/user/picker?query=email@domain.com` 

Not sure how to get this corrected, anyone else has found a better approach? Is this type of user lookup supported in any other way by the api?

**Comment by chesleybrown** [comment]
I encountered this as well. I'll submit a PR to resolve shortly.

For more context on this issue see [Deprecation notice and migration guide for major changes to Jira Cloud REST APIs to improve user privacy](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/).

> Changes to the visibility of user information: Users will be able to restrict the visibility of their personal data through their user profile privacy settings, or in the case of a managed account, the visibility settings that are decided by the site administrator. This means that fields such as email will only be returned by the API if the user has permitted that data to be visible. Note that this means that some fields can be null. The REST API changes will be introduced alongside the existing REST API. The existing REST API will be available until the end of the deprecation period. Until this time, you can use either the GDPR-compliant or non-GDPR compliant version of the REST API. An opt-in mechanism is available which will force Jira Cloud to only use the GDPR-compliant version of the REST API (that is, deprecated data is not used).

and [specifically around the user endpoints](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/#user)

> query parameter must be used to search for a user.

**Comment by chesleybrown** [comment]
Oh, if you need something more immediate, my workaround was:

```js
// TODO: unable to use client.searchUsers as it has not been updated
// to support the `query` parameter and using the `username` parameter
// fails with: The query parameter 'username' is not supported in GDPR strict mode.
//
// const users = await client.searchUsers({ username: email }) // fails because of GDPR
// const users = await client.searchUsers({ query: email }) // not supported by jira-client package
const users = await client.doRequest(client.makeRequestHeader(client.makeUri({
  pathname: '/user/search',
  query: {
    query: email,
    startAt: 0,
    maxResults: 50,
    includeActive: true,
    includeInactive: false
  }
}), {
  followAllRedirects: true
}))
```

**Comment by pioug** [comment]
Thanks people! I pushed an new version https://github.com/jira-node/node-jira-client/releases/tag/v6.17.0
