### ISSUE TITLE
are working the listFieldOptions and getFieldOption functions?

### ISSUE THREAD

**Issue by sanslash332** [jira-node/node-jira-client#288]
I'm testing both functions on my jira server (with api2) and both of them aren't working; all answers null.

When you check the error, the function make calls to /rest/api/2/field/customfield_17337/option

but when you check the documentation for the jira api (v2) says that the url for get customFields options is:

/rest/api/2/customfield/customfield_17337/option

The first url is correct too and is a problem of my jira-server?
Or is necessary check the lib?

Thanks for your support.

**Comment by randyho-kk** [comment]
Field options is an area that has an awkward implementation in the JIRA REST API. It depends on how the field was created.

If you hit the rest endpoints directly, which one returns your expected response?

https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-group-Issue-custom-field-options
https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-group-Issue-custom-field-options--apps-

**Comment by sanslash332** [comment]
hello! @randyho-kk

Noup, when I hit directly the jira server using these requests, it doesn't work. I have to use this other api (createMeta for issue endpoint)

/rest/api/2/issue/createmeta?projectKeys=MyProjectKey&issuetypeIds=SpecificIssueType&expand=projects.issuetypes.fields

With that I can get all valid values for all custom fields defined for that issuetype, but... Kmon jira, is very weird that path to get that simple information.

I had to follow this article on jira documentation to find that solution.

https://confluence.atlassian.com/jirakb/how-to-retrieve-available-options-for-a-multi-select-customfield-via-jira-rest-api-815566715.html

Maybe be a temporal option add to the jira-client the createMeta or editMeta functions?

Is funny how jira don't solve this-... considering that linked article is from... 4 years ago.

So well. thanks @randyho-kk for your valued support. Thanks for your library! is awesome!

**Comment by randyho-kk** [comment]
Ah glad you found the workaround.  Looks like you're correct that cascading select field options aren't available via the API.  I'm going to mark this issue as an enhancement for us to add getCreateIssueMeta and getEditIssueMeta functions to the API.

https://docs.atlassian.com/jira/REST/latest/#api/2/issue-getCreateIssueMeta
https://docs.atlassian.com/jira/REST/latest/#api/2/issue-getEditIssueMeta

I'm not the owner or major contributor of this repo.  Credit goes to all the brilliant folks who's contributed over the years.

**Comment by randyho-kk** [comment]
Looks like you beat me to it with the enhancement request in another issue so i'm going to close this one out.
