### ISSUE TITLE
Story points field

### ISSUE THREAD

**Issue by rajatkhare619** [jira-node/node-jira-client#294]
Hi,

I used the jira.findIssue() method to get the issue details, but I couldn't find story points. Is there a way I can get that field? There are a lot of custom fields though.

**Comment by randyho-kk** [comment]
story points would be one of the customfields.  You'll need to lookup which customfield story points are stored in on your system.  See this thread for guidance on looking up customfields: https://community.atlassian.com/t5/Jira-Core-questions/How-to-find-out-field-id/qaq-p/140555
