### ISSUE TITLE
createVersion and updateVersion Implementation and Types

### ISSUE THREAD

**Issue by dougmaitelli** [jira-node/node-jira-client#306]
Looking at the source code here:
https://github.com/jira-node/node-jira-client/blob/22b39c6844d43b898b9976cbc86ac1b0f53549ba/src/jira.js#L532

It seems there is some unclear information between the methods createVersion and updateVersion, the first says on comments the parameter is an object, the second says it is a string. But looking at the code it seems both are actually expecting an object in fact.

This caused the types from DefinitelyTyped to list both of them as string somehow, and when using this library on typescript it is impossible to use the createVersion method.

Can you please provide some light on that?

**Comment by pioug** [comment]
@dougmaitelli Seems like a mistake. Can you create a PR to change string to object?

**Comment by dougmaitelli** [comment]
You mean like this? https://github.com/jira-node/node-jira-client/pull/309
That would be a simple / short comment doc change then.

**Comment by dougmaitelli** [comment]
Does anyone have experience contributing to DefinitelyTyped to fix the types there?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jira-client/index.d.ts#L59

**Comment by pioug** [comment]
Thanks for the PR. I updated the package. 

I personnaly never contributed to DefinitelyTyped. It's out of our control, so you have to check with them directly 💦
