### ISSUE TITLE
oAuth feature request

### ISSUE THREAD

**Issue by VizinteanuGeorge** [jira-node/node-jira-client#308]
Hi! I was looking at this project, and I noticed to you have support for oAuth 1.0 in Jira. Would it be a good idea to add some utilities for the oAuth dance as well?  An example of this can be found [at this archived library](https://github.com/floralvikings/jira-connector/blob/master/lib/oauth_util.js). I think it would be a great addition, and I'm open to a PR.

**Comment by pioug** [comment]
For me, that doesn't fit in this project. I think it's already possible to pass access token issued by OAuth. That's where I draw the line.

OAuth is not trivial. We would need to include another dependency. Then everyone would have to install it even if they don't use it. So it's better to create a separate package that does only OAuth and combine it with an API wrapper.
