### ISSUE TITLE
Cannot connect to JIRA with NodeJS

### ISSUE THREAD

**Issue by dimisizz** [jira-node/node-jira-client#310]
This is my code:

```
const jiraApi = require('jira-client');

var jira = new jiraApi({protocol: 'https',
     host: 'jira.XXXX.global',
     username: 'myUsername',
     password: 'myPassword',
     apiVersion: '2'});

jira.findIssue('myIssueNumber').then(() => {
     console.log(`Status: ${issue.fields.status.name}`
)}).catch((error) => {
     console.log(error)});
```

I expect the program to print issue.fields.status.name in my terminal but I encounter Request failed with status code 401.

I am sure my username and password are correct because I can access JIRA application via chrome and I can see the detail of this IssueNumber.

I don't know why I encounter 401 error. Can anyone help me?

**Comment by mtjandra-applyboard** [comment]
What `password` are you using? You may need to specify an API token

> Specify a password for this tool to authenticate all requests with. Cloud users need to generate an API token for this value.

https://confluence.atlassian.com/cloud/api-tokens-938839638.html

**Comment by dimisizz** [comment]
@mtjandra-applyboard  I tried using the password I used to login JIRA via chrome and tried using API token generated from https://id.atlassian.com/manage/api-tokens. Nothing is working. I think my JIRA is not cloud version. I think it is server version.

**Comment by fhiutc** [comment]
```
const client = new JiraApi({
    protocol: "http",
    host: config.jiraUrl,
    username: config.jiraUsername,
    password: config.jiraToken,
    apiVersion: "2",
    strictSSL: false
});

```

try add > protocol: "http" ?

**Comment by fhiutc** [comment]
You may forget add `strictSSL: false` if you are using self-host jira.

**Comment by BenAlderfer** [comment]
I am also attempting to authenticate using an api token and I have not had success. I'm getting a deprecation error: 
`401 - "Basic authentication with passwords is deprecated.  For more information, see: https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html\n"`

When directly calling the api, I can just set this header: `Authorization: 'Basic ${apiToken}'`, is there an equivalent option I could pass here? I noticed that using the api token as a password also requires I add a username which should not be needed

**Comment by pioug** [comment]
> I noticed that using the api token as a password also requires I add a username which should not be needed

@BenAlderfer Not sure where this assumption comes from but the documentation clearly says that the **user's email is needed**. See https://confluence.atlassian.com/cloud/api-tokens-938839638.html

![image](https://user-images.githubusercontent.com/3654180/96195455-6550f600-0f7f-11eb-8cf7-c02e62442287.png)

**Comment by BenAlderfer** [comment]
@pioug I was referring to basic auth which actually does have the username in it, but its encoded with the token into a single string: https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/#supplying-basic-auth-headers

**Comment by pioug** [comment]
@BenAlderfer Oh ok. No, I don't think it's possible to set directly the authorization header.

**Comment by HrithikRaj1999** [comment]
This is working for me for jira-client@^8.2.2

```javascript
exports.loginJira = async function (username, password, bearerToken) {
  let jiraObj = {
    protocol: "https",
    host: someObject.jira.url,
    apiVersion: "2",
    strictSSL: true,
    bearer: bearerToken,
  };
  if (bearerToken) {
    jiraObj.bearer = bearerToken;
  } else {
    jiraObj.username = username;
    jiraObj.password = password;
  }

  let jira = new JiraApi(jiraObj);

  return jira
    .getCurrentUser()
    .then((result) => {
      console.log("Login Success");
      return { result, message: "Login successful", success: true };
    })
    .catch((err) => {
      console.log("Login Failed Check creds");
      return { err, message: "Login unsuccessful", success: false };
    });
};
```
