### ISSUE TITLE
Update worklogs API

### ISSUE THREAD

**Issue by dtlhlbs** [jira-node/node-jira-client#341]
Hi, I'm looking for an API call to update worklogs: https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-worklogs/#api-rest-api-3-issue-issueidorkey-worklog-id-put

It doesn't look like this is available in this node client? Can we add it? This is critical to help me with tracking projects to add my own metadata to worklogs.

> **Additional Properties**
> anything
> 
> Extra properties of any type may be provided to this object.

**Comment by Seth10001** [comment]
#349 should fix this
