### ISSUE TITLE
getLastSprintForRapidView uses wrong url

### ISSUE THREAD

**Issue by apalanki** [jira-node/node-jira-client#35]
Shouldn't the getLastSprintForRapidView use the greenhopper url instead of rest api?

For example:  http://jira.domain.com/rest/api/2/sprintquery/1461
returns 404 response

while http://jira.domain.com/rest/greenhopper/1.0/sprintquery/1461
returns valid response.

**Comment by KanoYugoro** [comment]
Sorry about that.  This is another thing that got garbled up when I did the re-write.  I've written up a PR and will be doing a patch release for this.  In the future, don't be afraid to write up a pull request if you have time, we do accept them! :smile:

**Comment by apalanki** [comment]
Thanks for the quick fix. Sure :)
