### ISSUE TITLE
addComment does not work

### ISSUE THREAD

**Issue by pixartist** [jira-node/node-jira-client#363]
It looks like the add comment method does not actually do anything. All I get is a response with
`{"startAt":0,"maxResults":5000,"total":0,"comments":[]}`
no comment is added, no error is thrown.

**Comment by pixartist** [comment]
The issues is apparently that the payload has a body object inside the body object:
```
{
      body: {
        body: comment,
      },
```

**Comment by ghost** [comment]
`jira.addComment("ISSUE-xxx", "Some comment")`

**Comment by Seth10001** [comment]
What @jonbeacherdomuso sent seems to work for me. Closing for now, please comment back if you have more info
