### ISSUE TITLE
Missing updateWorklog API

### ISSUE THREAD

**Issue by Vedinsoh** [jira-node/node-jira-client#367]
Hi, I'm running the latest version of the package 8.2.2 that's supposed to have `updateWorklog` function as per #341, however that doesn't seem to be the case.

**Comment by Seth10001** [comment]
Just tested on a fresh copy and it does for me. Could you confirm your package.json has 8.2.2 and it's installed?

**Comment by Vedinsoh** [comment]
Seems like it's indeed present in the package, but it's missing from `@types/jira-client`. Thought it wasn't published yet as I'm using it in a TypeScript project. I appreciate your response anyhow!
