### ISSUE TITLE
oauth_problem=signature_invalid when attempting to authenticate using OAuth

### ISSUE THREAD

**Issue by Plazmaz** [jira-node/node-jira-client#44]
When attempting to authenticate using OAuth, the request seems to fail with the message signature_invalid. The output is:
`401 - oauth_problem=signature_invalid&oauth_signature=ivO30fqXNHmgWJw5W8nn1RnG22mLRJSu6GO8Rw%2BLc7EYfbiN9ebpHjj2e6O098djpjCYxmdX%2FgTgdppyLOAad5dfSrepe%2F17BovqUskEtG7T6w0sG93aEvqNHZ5BJMpQm%2FP9aY%2Fb2%2FlLXT1TIKrwkU0q6B35MPlHdQjkqSp1vVbOHj4b%2BNHADrieOKOExWdEBuQgIX4J4gJQHrtIbjovMRo1n7pA5Ax9%2FvgRoOmsFulLpY%2FzrtwSlin5nZUGPCYr8UpHMdLbTMhr3OFoGk5PT6ilLpz%2F0XAT9teQ%2FM3Tzwhu6Goje619xg%2Fri2TxrctxBTgOPrnnQLHinuUEiSuSAg%3D%3D&oauth_signature_base_string=GET%26https%253A%252F%252Ftravis.atlassian.net%252Frest%252Fapi%252Flatest%252Fproject%252FGP%26oauth_consumer_key%253D<redacted>%2526oauth_nonce%253D596298020b7442da89751fb6eacc914f%2526oauth_signature_method%253DRSA-SHA1%2526oauth_timestamp%253D1459272339%2526oauth_token%253DEQL3QdfAOgFYH56YrMqycRXB4IdjMy55%2526oauth_version%253D1.0&oauth_signature_method=RSA-SHA1`

**Comment by KanoYugoro** [comment]
I really haven't the faintest idea on how to debug this or what the problem is.  We don't personally use oauth, so we accepted a PR from a developer for its support.  If you find a solution, you're welcome to write a pull request to implement it.

Maybe @mtscout6 or @attrib know more.

**Comment by attrib** [comment]
Can you post how you create the JiraClient?

**Comment by Plazmaz** [comment]
Here's how I'm creating the JiraClient:
https://gist.github.com/Plazmaz/d42454b2e7442bf73480f7a37673e06d

**Comment by Plazmaz** [comment]
However, this https://gist.github.com/Plazmaz/0fe59e1beb1285ba33c1819e5b84ab10 appears to function properly.

**Comment by attrib** [comment]
@Plazmaz could it be, that you use 443 as config.port? Don't! Do not use port if it is the standard port.
Otherwise I have to do a deeper look on the weekend.

**Comment by Plazmaz** [comment]
@attrib I was indeed using 443 as config.port. I don't know if this would've resolved the issue, as I've since migrated the project to use only node.js's OAuth library.
