### ISSUE TITLE
[question] How to create a new test cycle 

### ISSUE THREAD

**Issue by manoj9788** [jira-node/node-jira-client#53]
Would like to know, How to create a new test cycle.
I know its a Zephyr plugin  to JIRA. Any suggestion, how should I go about it ?

**Comment by mtscout6** [comment]
We don't cater to plugins directly in this module, nor am I familiar with the Zephyr plugin and it's available REST API. If you create a new npm module and get it released, we'd be more than happy to include that project as a part of this GitHub organization if you'd like. Though I don't think it would ever make it into this repo.

**Comment by mtscout6** [comment]
I'm going to close this because it falls out of scope with this project.
