### ISSUE TITLE
Can't set strictSSL to false

### ISSUE THREAD

**Issue by shaunburdick** [jira-node/node-jira-client#54]
Looking at line 22: `this.strictSSL = options.strictSSL || true;`, strictSSL will always be true:

```
$ node
> const obj = { strictSSL: false };
undefined
> obj.strictSSL || true;
true
```

**Comment by shaunburdick** [comment]
`this.strictSSL = options.hasOwnProperty('strictSSL') ? options.strictSSL : true;` seems to fix my problem :-)

**Comment by KanoYugoro** [comment]
Ah, good catch.  I'm rather busy this morning, but if you write a quick pull request, we can pull it in and cut a release for you today.

**Comment by shaunburdick** [comment]
Can do.
