### ISSUE TITLE
help：add watcher get 400 error

### ISSUE THREAD

**Issue by rongswu** [jira-node/node-jira-client#67]
`jira.addWatcher(issueId,"rong")`

StatusCodeError: 400 - undefined

**Comment by KanoYugoro** [comment]
There are a lot of things that could be causing the problem with the request this method is trying to make, so this will take some time to diagnose.  Make sure that the `issueId` you've specified is a valid one, including the project key.  Then, make sure that the user you're trying to add is being addressed correctly.

If both the username and the issueId you are passing in are valid, I do have one more thing you can try.  Some googling around has shown me as well that there could be a quirk with the jira rest API where you have to send escaped quotes inside of the string.  For example `"rong"` might need to be sent as `"\"rong\""`.

**Comment by rongswu** [comment]
@KanoYugoro Thank you for your reply.
I had try to send as \"rong\"", but it returned the same error.

**Comment by KanoYugoro** [comment]
We do use this API where I work, but we don't use this particular function.  If you look into the code, you should be able to find the rest API url that it is hitting with a quick search and double check it against Jira's documentation.  If you figure out that there is an issue, you are more than welcome to write a pull request to fix it and I will be happy to pull it in and get it released for you.  I would dig into this myself, but I don't have time to diagnose it right now.

**Comment by KanoYugoro** [comment]
I'm going to go ahead and close this.  It's been 13 days since last communication.

**Comment by technotronic12** [comment]
@KanoYugoro I am experiencing the same issue.
If you remove JSON.stringify(username) in the addWatcher method it works, 
so I guess @rongswu is right.
