### ISSUE TITLE
How to configure jira (and client) for oauth?

### ISSUE THREAD

**Issue by tishma** [jira-node/node-jira-client#72]
It's not really the issue with the library, but it's a shame that client lib has an option without a hint how to get to use it.

If anyone can help - please don't hesitate.

Thank you.

**Comment by KanoYugoro** [comment]
Sorry it's taken me so long to respond.  I didn't get a notification for this issue.  We don't currently use the oauth features of this library on our company's instance of JIRA, so I'm probably not going to be of too much health.  I do know in JIRA, access tokens have to be generated manually by a JIRA administrator if I'm not mistaken.  JIRA should have documentation on how to do this.

Once you have one, you just need to add a field named `oauth` to the options object that the constructor for the API takes in.  This oauth object needs to have the following fields on it:
```json
{
  consumer_key: "whatever the consumer key is",
  consumer_secret: "whatever your consumer_secret is",
  token: "your access token",
  token_secret: "the access token secret",
}
```

If you find our implementation to be incorrect, you are welcome to write a pull request to this repo and I will be more than happy to review and pull it in if it fixes the problem.  Perhaps @attrib can help you more?

**Comment by attrib** [comment]
Here a description how to set up OAuth. Its from our project which is not yet public (but will be soon). This part is already documented ;)

Retrieving the access token is the "hard" part if you application has no web interface. My description assumes this case and a "hack" to get the access token either way.

1. Generate a key
    openssl genrsa -out ~/.ssh/jira_rsa 2048
    openssl rsa -in ~/.ssh/jira_rsa -pubout > ~/.ssh/jira_rsa.pub

2. Setup Application in Jira (Preferences > Applications > Select Application Links /plugins/servlet/applinks/listApplicationLinks)

  * Application Name: <any name>
  * Application Type: General Application
  * Enable input link
  * Click continue
  * Consumer Key: <random string>
  * Consumer Name: <any name>
  * Public Key: <content from ~/.ssh/jira_rsa.pub>

3.  Get access token:

  * Create temp folder with oauth.js (https://gist.github.com/attrib/ea446d5cd25617cf14a2)
  * npm install oauth
  * Replace XXXXXX with consumer key
  * node oauth.js
  * Follow instructions and at the end iy will output access_token and access_token_secret

4. Now like @KanoYugoro mentioned add a oauth field to the config object

**Comment by tishma** [comment]
Thanks guys,
I think I'm almost there. At the moment I'm only missing a reference to consumer_secret on JIRA side. I'll play trial&error for a while, but if you have an idea - I'd appreciate if you share it here.
v.

**Comment by attrib** [comment]
@tishma consumer secret is the public key. You need to load your private key file, e.g.

`fs.readFileSync(process.env['HOME'] + '/.ssh/jira_rsa', "utf8")`

**Comment by tishma** [comment]
@attrib public or private? 
`consumer_secret: fs.readFileSync(process.env['HOME'] + '/.ssh/jira_rsa', "utf8"),`
would be correct, right?

**Comment by attrib** [comment]
@tishma For the consumer_secret its the private key.

**Comment by tishma** [comment]
@attrib Thank you so much! I've made my first oauth call!

**Comment by KanoYugoro** [comment]
Thanks @attrib !  I'm going to close this issue now.

**Comment by tishma** [comment]
@attrib FYI, there is a syntax error in your oauth.js (missing , after "RSA-SHA1")

**Comment by attrib** [comment]
@tishma Thanks for the hint and fixed it.
