### ISSUE TITLE
Request from behind corporate proxy

### ISSUE THREAD

**Issue by nicolas-mosch** [jira-node/node-jira-client#92]
I get the following error when using the listProjects function:
Error: connect EHOSTUNREACH (some IP address X)

I have seen this EHOSTUNREACH message before and it was caused by being behind a corporate proxy.
Is there a way of giving in proxy details to fix this (like the --proxy flag from curl)?

Cheers

**Comment by KanoYugoro** [comment]
Currently, there is no functionality to support a proxy of any sort.  To develop that functionality would take more time than I currently have to support this project.  If you or anyone you know would like to take the time, we do accept pull requests.
